### ISSUE TITLE
For Beginners 

### ISSUE THREAD

**Issue by rajasimon** [django-nonrel/django-testapp#12]
i just changed app.yaml application id only . Then i deploy into google appengine and its showing internal 500 server error ..

**Comment by timkofu** [comment]
Go to the app logs and paste the details of the last error log here.

**Comment by rajasimon** [comment]
Thanks for the replay ..

2014-04-24 11:30:35.955
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 298, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 84, in LoadObject
    obj = __import__(path[0])
ImportError: No module named djangoappengine

**Comment by timkofu** [comment]
If you hadnt done so, run $ ./build.sh it should dowload the necessary dependancies.

**Comment by rajasimon** [comment]
Oh .. s .. Ya thanks .. 

I did & everything fine except this in d requirements.txt 

-e git+http://github.com/django-nonrel/django@nonrel-1.4#egg=django-nonrel

and i change to this 

-e git+https://github.com/django-nonrel/django-1.4.git@nonrel-1.4#egg=django-nonrel

then also its not downloading the package so i manually install that package into my project folder
then deploy into my appengine application. Its working fine ( firstpoochedi.appspot.com ) and at the time of writing this time dev appserver also working fine ..

**Comment by rajasimon** [comment]
How to create admin login ? 

i have this error

e/firstpoochedi/manage.py createsuperuser
Traceback (most recent call last):
  File "workspace/google_appengine/dev_appserver.py", line 82, in <module>
    _run_file(__file__, globals())
  File "workspace/google_appengine/dev_appserver.py", line 78, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/home/vijay/workspace/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 917, in <module>
    main()
  File "/home/vijay/workspace/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 910, in main
    dev_server.start(options)
  File "/home/vijay/workspace/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 679, in start
    options.config_paths)
  File "/home/vijay/workspace/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 599, in **init**
    module_configuration = ModuleConfiguration(config_path)
  File "/home/vijay/workspace/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 97, in **init**
    self._config_path)
  File "/home/vijay/workspace/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 299, in _parse_configuration
    config, files = appinfo_includes.ParseAndReturnIncludePaths(f)
  File "/home/vijay/workspace/google_appengine/google/appengine/api/appinfo_includes.py", line 81, in ParseAndReturnIncludePaths
    appyaml = appinfo.LoadSingleAppInfo(appinfo_file)
  File "/home/vijay/workspace/google_appengine/google/appengine/api/appinfo.py", line 1873, in LoadSingleAppInfo
    listener.Parse(app_info)
  File "/home/vijay/workspace/google_appengine/google/appengine/api/yaml_listener.py", line 226, in Parse
    self._HandleEvents(self._GenerateEventParameters(stream, loader_class))
  File "/home/vijay/workspace/google_appengine/google/appengine/api/yaml_listener.py", line 172, in _HandleEvents
    for event in events:
  File "/home/vijay/workspace/google_appengine/google/appengine/api/yaml_listener.py", line 212, in _GenerateEventParameters
    raise yaml_errors.EventListenerYAMLError(e)
google.appengine.api.yaml_errors.EventListenerYAMLError: mapping values are not allowed here
  in "workspace/firstpoochedi/manage.py", line 3, column 4

**Comment by rajasimon** [comment]
Closing too old.
